# Generated by Django 3.2.16 on 2023-10-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_follow_name of constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='name of constraint',
        ),
    ]
